//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoQLNH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.BillDetails = new HashSet<BillDetail>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> dateCheckin { get; set; }
        public Nullable<System.DateTime> dateCheckout { get; set; }
        public string status { get; set; }
        public string sender { get; set; }
        public Nullable<int> moneyInput { get; set; }
        public Nullable<int> discount { get; set; }
        public int isDelete { get; set; }
        public int idTable { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public Nullable<int> idBookingTable { get; set; }
    
        public virtual BookingTable BookingTable { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Table Table { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
    }
}
